name = "open_linalg"
version = "0.2.3"
license = "MIT"
author = "zoziha"
maintainer = "zuo.zhihua@qq.com"
copyright = "Copyright 2022, zoziha"

[build]
auto-executables = false
auto-tests = false
auto-examples = true
link = ["openblas"]

[install]
library = true
